name: cppcheck

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          force: enable
          inline_suppression: enable
          enable: all
          other_options: --template=gcc --suppress=unusedFunction --suppress=redundantAssignment --suppress=variableScope --suppress=missingInclude
