name: Google Test

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: apt-update
      run: sudo apt-get update

    - name: Install boost
      run: sudo apt-get install -y libboost-all-dev
    - name: Install Google Test
      run: sudo apt-get install -y googletest libgtest-dev
    
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_BOOST=ON -DWITH_GTEST=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/scripts
      run: ${{github.workspace}}/scripts/rungtest.sh ${{github.workspace}}/build/test
